`rstan`: Revert to `stanc3` v2.29.2 (25 March 2022)
Temproarily use `stanc3` v2.29.2 to fixes the following exception:

```
Exception: variable does not exist; processing stage=data initialization; variable name=...
```