GHA: Use R-devel and R-oldrel only on Linux runners
To avoid unrelated failures due to unstable r-lib/actions such as:

```bash
Error: Failed to get R devel: Failed to get R devel: Failed to install R: Error: spawn UNKNOWN
```